config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "links#index"

  get 'tags/:tag', to: 'links#index', as: :tag
  resources :links, only: [:index, :new, :create, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :tags

  validates :title, :link, :tag_list, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_tagger
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if params[:tag]
        @links = Links.all.tagged_with(params[:tag]).order(created_at: :DESC)
      else
        @links = Link.all.order(created_at: :DESC)
    end
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.build(link_params)
    if @link.save
      flash[:success] = "Link created!"
      redirect_to links_path
    else
      flash.now[:danger] = "Link has not been created!"
      render 'new'
    end
  end

  def show
    link
  end

  def edit
    link
  end

  def update
    if link.update(link_params)
      flash[:info] = "Link updated!"
      redirect_to links_path
    else
      flash.now[:danger] = "Link has not been updated!"
      render 'edit'
    end
  end

  def destroy
    link.destroy
    flash[:danger] = "Link deleted!"
    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :link, :tag_list)
  end

  def link
    @link ||= Link.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Edutube
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/nav'
    = render 'shared/alerts'
    .container
      = yield

app/views/links/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for @link do |f|
      = render 'shared/errors', obj: @link
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :link
        = f.text_field :link, class: 'form-control'
      .form-group
        = f.label :tag_list
        = f.text_field :tag_list, class: 'form-control'
      = f.submit class: 'btn btn-primary'

app/views/links/edit.html.haml
%h1 Edit Link
= render 'form'

app/views/links/index.html.haml
- @links.each do |link|
  .panel.panel-default
    .panel-body
      = link_to link.title, link.link, target: :_blank
      %p
        Tags: #{raw link.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')}
      .author
        %small
          Created by: #{link.user.email}
    .panel-footer
      - if link.user == current_user
        = link_to "Edit", edit_link_path(link), class: 'btn btn-xs btn-default'
        = link_to "Delete", link_path(link), method: :delete, class: 'btn btn-xs btn-danger'

app/views/links/new.html.haml
%h1 New Link
= render 'form'

app/views/shared/_alerts.html.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-12
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this link from being saved:
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/shared/_nav.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to "EDUTUBE", root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-left
      - if user_signed_in?
        %li= link_to "Add new link", new_link_path
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li= link_to "LOG OUT", destroy_user_session_path, method: :delete
      - else
        %li= link_to "REGISTER", new_user_registration_path
        %li= link_to "LOG IN", new_user_session_path